<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CityTableRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'city' => 'required|min:2|max:200',
        ];
    }
    public function messages()
    {
        $messages = [
            'name.required' => 'We need to know your full name!',
            'name.min' => 'Name size must be between 2 and 200!',
            'name.max' => 'Name size must be between 2 and 200!',
        ];
        return $messages;  // TODO: Change the autogenerated stub
    }
}
